import React from 'react';
import { Loader } from './Loader';
import { DownloadIcon } from './icons/DownloadIcon';

interface ImageDisplayProps {
  imageUrl: string | null;
  isGenerating: boolean;
  generationTime: number;
}

const Placeholder: React.FC = () => (
  <div className="w-full h-full flex flex-col items-center justify-center text-center p-8 bg-gray-800/50 border-2 border-dashed border-gray-700 rounded-lg">
    <svg xmlns="http://www.w3.org/2000/svg" className="h-16 w-16 text-gray-600 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
    </svg>
    <h3 className="text-lg font-medium text-gray-300">Your generated image will appear here</h3>
    <p className="mt-1 text-sm text-gray-500">Fill out the form and click "Generate Image" to start.</p>
  </div>
);

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isGenerating, generationTime }) => {
  return (
    <div className="flex flex-col space-y-4">
      <div className="relative aspect-square w-full flex items-center justify-center rounded-lg bg-gray-900 overflow-hidden">
        {isGenerating && (
          <div className="absolute inset-0 bg-gray-900/80 backdrop-blur-sm z-10 flex flex-col items-center justify-center space-y-4 text-center p-4">
            <Loader />
            <p className="text-lg font-medium text-white">Generating your masterpiece...</p>
            <p className="text-gray-400">This can take a minute. The Stable Horde is powered by a volunteer-run distributed cluster.</p>
            <div className="text-indigo-400 font-mono text-xl">
               {(generationTime / 1000).toFixed(1)}s
            </div>
          </div>
        )}

        {imageUrl ? (
          <img
            src={imageUrl}
            alt="Generated by Stable Horde"
            className="object-contain w-full h-full transition-opacity duration-500 ease-in-out"
          />
        ) : !isGenerating && (
          <Placeholder />
        )}
      </div>

      {imageUrl && !isGenerating && (
        <a
          href={imageUrl}
          download="generated-image.png"
          className="w-full flex items-center justify-center gap-2 py-3 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 focus:ring-offset-gray-900 transition-all duration-300"
        >
          <DownloadIcon className="w-5 h-5" />
          Download Image
        </a>
      )}
    </div>
  );
};